apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-gqhy
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-gqhy
    app.kubernetes.io/part-of: tkrw-pr714-0075-0054-app
  name: devfile-sample-gqhy
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: devfile-sample-gqhy
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: devfile-sample-gqhy
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr714-0075-0054-tenant/tkrw-pr714-0075-0054-app/devfile-sample-gqhy@sha256:7ac98dc63320b090622f5e1197f85919f6a3a00a88934f6f768d8a9c1e7195ae
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
